name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      # 创建本地的Android虚拟机
      - name: run androidTestSdk on API 28 emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          target: default
          arch: x86_64
          profile: pixel_xl
          script: ./gradlew androidTestSdk

      # 打印出adb已连接的Android设备
      - name: adb devices -l 
        run : adb devices -l 
